=== F2I-Consulting/fesapi/gsoap/PropertyTypeMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.f2i-consulting.com/PropertyTypeMapping" xmlns:ptm="http://www.f2i-consulting.com/PropertyTypeMapping" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified">
	<xsd:import namespace="http://www.energistics.org/energyml/data/resqmlv2" schemaLocation="RESQML_SCHEMA_LOCATION/Common.xsd"/>
	<xsd:element name="standardEnergisticsPropertyTypeSet" type="ptm:standardEnergisticsPropertyTypeSet">
		<xsd:annotation>
			<xsd:documentation>A container for enumeration lists.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<!--                                                         -->
	<xsd:complexType name="standardEnergisticsPropertyTypeSet">
		<xsd:sequence>
			<xsd:element name="standardEnergisticsPropertyType" type="ptm:standardEnergisticsPropertyType" minOccurs="1" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>A single enumeration list.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:complexType name="standardEnergisticsPropertyType">
		<xsd:sequence>
			<xsd:element name="name" type="resqml:ResqmlPropertyKind" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A description of the value. </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="version" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The version when the value was added.
					The string should match the content of the root version attribute of the schema.
					For example, "1.4.0.0".</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="deprecated" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A non blank version indicates that the value has
					been deprecated and may be removed in future versions.
					The string should match the content of the root version attribute of the schema.
					For example, "1.4.0.0".</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="replacedBy" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The value to use as a replacement for a deprecated value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="isAbstract" type="xsd:boolean" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>True ("1" or "true") indicates that the property is abstract and cannot be used to characterize a value.
					False ("0" or "false") or not given indicates a non-abstract property that can be instantiated.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="parentKind" type="xsd:string" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Points to a parent property kind</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="equivalentPropertyType" type="ptm:equivalentPropertyType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>	
	<!--                                                         -->
	<xsd:complexType name="equivalentPropertyType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="namingSystem" type="xsd:string" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</schema>

=== F2I-Consulting/fesapi/resources/PropertyKindMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<standardEnergisticsPropertyTypeSet xmlns="http://www.f2i-consulting.com/PropertyTypeMapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.f2i-consulting.com/PropertyTypeMapping PropertyTypeMapping.xsd ">
	<standardEnergisticsPropertyType>
		<name>absorbed dose</name>
		<description>The amount of energy absorbed per mass.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>acceleration linear</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>activity (of radioactivity)</name>
		<description>A measure of the radiation being emitted.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>amount of substance</name>
		<description>Molar amount of a substance.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Amount of substance</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>amplitude</name>
		<description>Amplitude of the acoustic signal recorded. It is not a physical property, only a standardEnergisticsPropertyType.</description>
		<isAbstract>false</isAbstract>
		<parentKind>unitless</parentKind>
		<equivalentPropertyType>
			<name>Seismic (default)</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angle per length</name>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angle per time</name>
		<description>The angular velocity. The rate of change of an angle.</description>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angle per volume</name>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>angular acceleration</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>area</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Area</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>area per area</name>
		<description>A dimensionless quantity where the basis of the ratio is area.</description>
		<isAbstract>true</isAbstract>
		<parentKind>dimensionless</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>area per volume</name>
		<isAbstract>true</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>attenuation</name>
		<description>A logarithmic, fractional change of some measure, generally power or amplitude, over a standard range. This is generally used for frequency attenuation over an octave.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>attenuation per length</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>azimuth</name>
		<description>Angle between the North and the projection of the normal to the horizon surface estimated on a local area of the interface.</description>
		<isAbstract>false</isAbstract>
		<parentKind>plane angle</parentKind>
		<equivalentPropertyType>
			<name>Dip azimuth</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>bubble point pressure</name>
		<description>The pressure at which the first gas bubble appears while decreasing pressure on a fluid sample.</description>
		<isAbstract>false</isAbstract>
		<parentKind>pressure</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>bulk modulus</name>
		<description>Bulk modulus, K</description>
		<isAbstract>false</isAbstract>
		<parentKind>pressure</parentKind>
		<equivalentPropertyType>
			<name>Bulk modulus</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>capacitance</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>categorical</name>
		<description>The abstract supertype of all enumerated string properties.</description>
		<isAbstract>true</isAbstract>
		<parentKind>RESQML root property</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>cell length</name>
		<description>distance from cell face center to cell face center in the specified direction, DI, DJ, DK</description>
		<isAbstract>false</isAbstract>
		<parentKind>length</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>charge density</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>chemical potential</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>code</name>
		<description>A discrete code.</description>
		<isAbstract>false</isAbstract>
		<parentKind>categorical</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>compressibility</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>concentration of B</name>
		<description>molar concentration of a substance.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>conductivity</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Conductivity</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>continuous</name>
		<description>The abstract supertype of all floating point properties.</description>
		<isAbstract>true</isAbstract>
		<parentKind>RESQML root property</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>cross section absorption</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Photoelectric factor</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>current density</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>Darcy flow coefficient</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>data transmission speed</name>
		<description>used primarily for computer transmission rates.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>delta temperature</name>
		<description>Delta temperature refers to temperature differences. For non-zero offset temperature scales, Fahrenheit and Celsius, the conversion formulas are different than for absolute temperatures.</description>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Differential temperature</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>density</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Density</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>depth</name>
		<description>The perpendicular measurement downward from a surface. Also, the direct linear measurement from the point of viewing usually from front to back.</description>
		<isAbstract>false</isAbstract>
		<parentKind>length</parentKind>
		<equivalentPropertyType>
			<name>Elevation depth</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>diffusion coefficient</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
		<equivalentPropertyType>
			<name>Diffusivity</name>
			<namingSystem>Petrel</namingSystem>
		</equivalentPropertyType>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>digital storage</name>
		<isAbstract>false</isAbstract>
		<parentKind>quantity</parentKind>
	</standardEnergisticsPropertyType>
	<standardEnergisticsPropertyType>
		<name>dimensionless</name>
